#!/usr/bin/env bash
# setup-camofox.sh — Install CamoFox + Phantom Wallet for ResonantOS vNext
#
# Downloads:
#   - Camoufox binary via camoufox-js (npx camoufox-js fetch)
#   - Phantom Wallet .xpi from Mozilla Addons
#
# Creates a browser profile with Phantom pre-installed at:
#   ~/.camofox/profiles/resonantos/
#
# Usage:
#   ./scripts/setup-camofox.sh          # install (skip if exists)
#   ./scripts/setup-camofox.sh --force   # re-download everything

set -euo pipefail

PHANTOM_XPI_URL="https://addons.mozilla.org/firefox/downloads/latest/phantom-app/addon-phantom-app-latest.xpi"
PHANTOM_ADDON_ID="{7c42eea1-b3e4-4be4-a56f-82a5852b12dc}"
PROFILE_DIR="${HOME}/.camofox/profiles/resonantos"
ADDON_DIR="${HOME}/.camofox/addons"
FORCE=false

[[ "${1:-}" == "--force" ]] && FORCE=true

echo "═══════════════════════════════════════════"
echo "  CamoFox Setup — ResonantOS vNext"
echo "═══════════════════════════════════════════"

# ── Step 1: Install Camoufox binary ──────────────────────
echo ""
echo "▸ Step 1: Camoufox binary"

# Check if already installed
CAMOFOX_BIN=""
if [[ "$(uname)" == "Darwin" ]]; then
    CAMOFOX_BIN="${HOME}/Library/Caches/camoufox/Camoufox.app/Contents/MacOS/camoufox"
elif [[ "$(uname)" == "Linux" ]]; then
    CAMOFOX_BIN="${HOME}/.cache/camoufox/camoufox"
else
    # Windows (Git Bash / MSYS2)
    CAMOFOX_BIN="${LOCALAPPDATA}/camoufox/camoufox.exe"
fi

if [[ -f "$CAMOFOX_BIN" ]] && [[ "$FORCE" == false ]]; then
    echo "  ✅ Already installed: $CAMOFOX_BIN"
else
    echo "  Downloading Camoufox (~300MB)..."
    # Pin to a specific version for reproducible installs.
    # To upgrade: test the new release manually, then update the version here.
    npx camoufox-js@0.4.11 fetch
    if [[ -f "$CAMOFOX_BIN" ]]; then
        echo "  ✅ Installed: $CAMOFOX_BIN"
    else
        echo "  ❌ Binary not found after install. Check camoufox-js output."
        exit 1
    fi
fi

# ── Step 2: Download Phantom Wallet ─────────────────────
echo ""
echo "▸ Step 2: Phantom Wallet extension"

mkdir -p "$ADDON_DIR"
PHANTOM_XPI="$ADDON_DIR/phantom.xpi"

if [[ -f "$PHANTOM_XPI" ]] && [[ "$FORCE" == false ]]; then
    echo "  ✅ Already downloaded: $PHANTOM_XPI"
else
    echo "  Downloading Phantom Wallet (~14MB)..."
    curl -sL "$PHANTOM_XPI_URL" -o "$PHANTOM_XPI"
    if [[ -f "$PHANTOM_XPI" ]] && [[ $(stat -f%z "$PHANTOM_XPI" 2>/dev/null || stat -c%s "$PHANTOM_XPI" 2>/dev/null) -gt 1000000 ]]; then
        # Log the SHA-256 of the downloaded XPI to enable future hash pinning.
        # Strategy: once a known-good hash is confirmed across multiple installs,
        # add a comparison here to detect supply-chain tampering.
        # Example enforcement (when hash is known):
        #   EXPECTED_SHA256="<known-good-hash>"
        #   [[ "$PHANTOM_SHA256" == "$EXPECTED_SHA256" ]] || { echo "❌ Hash mismatch"; exit 1; }
        PHANTOM_SHA256=$(shasum -a 256 "$PHANTOM_XPI" 2>/dev/null | awk '{print $1}' \
            || sha256sum "$PHANTOM_XPI" 2>/dev/null | awk '{print $1}')
        echo "  ✅ Downloaded: $PHANTOM_XPI"
        echo "  📋 SHA-256: ${PHANTOM_SHA256:-unknown}"
    else
        echo "  ❌ Download failed or file too small."
        exit 1
    fi
fi

# ── Step 3: Create profile with Phantom ─────────────────
echo ""
echo "▸ Step 3: Browser profile"

EXT_DIR="$PROFILE_DIR/extensions/$PHANTOM_ADDON_ID"

if [[ -d "$EXT_DIR/manifest.json" ]] && [[ "$FORCE" == false ]]; then
    echo "  ✅ Profile exists: $PROFILE_DIR"
else
    echo "  Creating profile at $PROFILE_DIR..."
    mkdir -p "$EXT_DIR"
    
    # Extract Phantom into profile extensions directory
    echo "  Extracting Phantom extension..."
    unzip -o "$PHANTOM_XPI" -d "$EXT_DIR" > /dev/null 2>&1
    
    if [[ -f "$EXT_DIR/manifest.json" ]]; then
        echo "  ✅ Phantom installed in profile"
    else
        echo "  ❌ Extension extraction failed."
        exit 1
    fi
fi

# ── Step 4: Write Firefox preferences ───────────────────
echo ""
echo "▸ Step 4: Firefox preferences"

cat > "$PROFILE_DIR/user.js" << 'PREFS'
// CamoFox profile for ResonantOS vNext
// Auto-generated by setup-camofox.sh — do not edit manually

// === EXTENSION SIDELOADING ===
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.enabledScopes", 15);
user_pref("xpinstall.signatures.required", false);

// === MV3 EXTENSION SUPPORT (CRITICAL for Phantom Wallet) ===
// Without these, MV3 extensions cannot start their background service worker
// and content script injection fails silently.
user_pref("extensions.manifestV3.enabled", true);
user_pref("extensions.eventPages.enabled", true);
user_pref("extensions.backgroundServiceWorker.enabled", true);
user_pref("dom.serviceWorkers.enabled", true);
user_pref("dom.serviceWorkers.testing.enabled", true);
user_pref("extensions.startupScanScopes", 15);
user_pref("extensions.install.requireBuiltInCerts", false);
user_pref("extensions.update.enabled", false);

// === MARIONETTE ===
user_pref("marionette.port", 2828);

// === SUPPRESS FIRST-RUN NOISE ===
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.warnOnQuit", false);

// === PERFORMANCE ===
user_pref("media.autoplay.default", 5);
user_pref("reader.parse-on-load.enabled", false);
user_pref("browser.pocket.enabled", false);
user_pref("extensions.pocket.enabled", false);
PREFS

echo "  ✅ Preferences written"

# ── Step 5: Set permissions ─────────────────────────────
echo ""
echo "▸ Step 5: Security"

chmod -R 700 "$PROFILE_DIR"
chmod 700 "$ADDON_DIR"
echo "  ✅ Profile permissions set (owner-only)"

# ── Step 6: Smoke test ──────────────────────────────────
echo ""
echo "▸ Step 6: Smoke test"

echo "  Launching CamoFox (5s test)..."
"$CAMOFOX_BIN" -profile "$PROFILE_DIR" -marionette -no-remote --headless &
SMOKE_PID=$!
sleep 5

# Check if Marionette is listening
if command -v nc &> /dev/null; then
    if nc -z 127.0.0.1 2828 2>/dev/null; then
        echo "  ✅ Marionette responding on port 2828"
    else
        echo "  ⚠️  Marionette not detected (may need more time)"
    fi
else
    echo "  ⚠️  nc not available, skipping port check"
fi

kill "$SMOKE_PID" 2>/dev/null
wait "$SMOKE_PID" 2>/dev/null

# ── Done ────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════"
echo "  ✅ CamoFox setup complete!"
echo ""
echo "  Binary:  $CAMOFOX_BIN"
echo "  Profile: $PROFILE_DIR"
echo "  Phantom: $EXT_DIR"
echo ""
echo "  To launch manually:"
echo "    $CAMOFOX_BIN -profile $PROFILE_DIR -marionette -no-remote --kiosk"
echo "═══════════════════════════════════════════"
