import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..", "..");
const browserFirstRoot = path.join(repoRoot, "browser-first");
const extensionRoot = path.join(browserFirstRoot, "resonantos-side-panel-extension");

const readJson = async (filePath) => JSON.parse(await readFile(filePath, "utf8"));
const readText = (filePath) => readFile(filePath, "utf8");

test("ADR-037 makes browser-first Chromium the product direction", async () => {
  const adr = await readText(path.join(repoRoot, "docs", "architecture", "ADR-037-browser-first-chromium-resonantos.md"));
  const adr035 = await readText(path.join(repoRoot, "docs", "architecture", "ADR-035-electron-host-rust-core-runtime.md"));
  const adr036 = await readText(path.join(repoRoot, "docs", "architecture", "ADR-036-wallet-capable-browser-host.md"));

  assert.match(adr, /browser-first application/i);
  assert.match(adr, /Chromium-family browser/i);
  assert.match(adr, /not a ResonantOS dashboard that opens or controls another browser/i);
  assert.match(adr, /Phantom Wallet must run in the same browser profile/i);
  assert.match(adr, /Do not present external Chrome\/Brave CDP control as the product Browser/i);
  assert.match(adr035, /Superseded by ADR-037/);
  assert.match(adr036, /Superseded by ADR-037/);
});

test("ResonantOS browser layer is packaged as a Chromium side-panel extension", async () => {
  const manifest = await readJson(path.join(extensionRoot, "manifest.json"));

  assert.equal(manifest.manifest_version, 3);
  assert.equal(manifest.name, "ResonantOS Browser Layer");
  assert.equal(manifest.version, "0.1.1");
  assert.equal(manifest.key.length > 100, true);
  assert.ok(manifest.permissions.includes("sidePanel"));
  assert.ok(manifest.permissions.includes("activeTab"));
  assert.ok(manifest.permissions.includes("audioCapture"));
  assert.ok(manifest.permissions.includes("clipboardRead"));
  assert.ok(manifest.permissions.includes("clipboardWrite"));
  assert.ok(manifest.permissions.includes("history"));
  assert.ok(manifest.permissions.includes("scripting"));
  assert.ok(manifest.permissions.includes("tabs"));
  assert.ok(manifest.permissions.includes("webNavigation"));
  assert.equal(manifest.content_scripts[0].all_frames, true);
  assert.equal(manifest.side_panel.default_path, "src/side-panel.html");
  assert.equal(manifest.chrome_url_overrides, undefined);
  assert.equal(manifest.background.type, "module");
  assert.equal(manifest.background.service_worker, "src/background.js");
  assert.equal(manifest.commands["open-augmentor-side-panel"].suggested_key.mac, "Alt+Shift+A");
});

test("browser-first main workspace owns new-tab AI chat and hands browser tasks to the sidebar", async () => {
  const manifest = await readJson(path.join(extensionRoot, "manifest.json"));
  const workspace = await readText(path.join(extensionRoot, "src", "main-workspace.html"));
  const workspaceScript = await readText(path.join(extensionRoot, "src", "main-workspace.js"));
  const workspaceStyles = await readText(path.join(extensionRoot, "src", "main-workspace.css"));
  const promptRouter = await readText(path.join(extensionRoot, "src", "lib", "main-workspace-prompt-router.js"));
  const launcher = await readText(path.join(browserFirstRoot, "host", "run-browser-first.mjs"));
  const archiveMerge = await readText(path.join(browserFirstRoot, "host", "archive-merge.mjs"));
  const background = await readText(path.join(extensionRoot, "src", "background.js"));
  const sidePanel = await readText(path.join(extensionRoot, "src", "side-panel.js"));
  const commandRouter = await readText(path.join(extensionRoot, "src", "lib", "side-panel-command-router.js"));
  const appCommandHandlers = await readText(path.join(extensionRoot, "src", "lib", "app-command-handlers.js"));
  const workspaceSettings = await readText(path.join(extensionRoot, "src", "lib", "main-workspace-settings.js"));
  const workspaceRail = await readText(path.join(extensionRoot, "src", "lib", "main-workspace-rail.js"));
  const diagnosticsSettings = await readText(path.join(extensionRoot, "src", "lib", "settings", "diagnostics-section.js"));
  const aboutSettings = await readText(path.join(extensionRoot, "src", "lib", "settings", "about-section.js"));
  const browserControlSettings = await readText(path.join(extensionRoot, "src", "lib", "settings", "browser-control-section.js"));

  assert.equal(manifest.chrome_url_overrides, undefined);
  assert.match(workspace, /ResonantOS main workspace/);
  assert.match(workspace, /New chat/);
  assert.match(workspace, /Search chats/);
  assert.match(workspace, /Pinned Add-ons/);
  assert.doesNotMatch(workspace, /aria-label="Pinned"/);
  assert.match(workspace, /Projects/);
  assert.match(workspace, /rail-new-project/);
  assert.match(workspace, /rail-project-list/);
  assert.match(workspace, /Chats/);
  assert.match(workspace, /rail-chat-list/);
  assert.doesNotMatch(workspace, /ResonantOS Architecture/);
  assert.match(workspace, /Artifacts/);
  assert.match(workspace, /Add-ons/);
  assert.match(workspace, /Living Archive/);
  assert.match(workspace, /Hermes/);
  assert.match(workspace, /OpenCode/);
  assert.match(workspace, /Settings/);
  assert.doesNotMatch(workspace, /System Settings/);
  assert.match(workspace, /model-select/);
  assert.match(workspace, /thinking-depth/);
  assert.match(workspace, /read-page/);
  assert.match(workspace, /save-intake/);
  assert.match(workspace, /save-selection/);
  assert.match(workspace, /context-toggle/);
  assert.match(workspace, /context-meter/);
  assert.match(workspace, /dictate-button/);
  assert.match(workspace, /title="Read current browser page"/);
  assert.match(workspace, /title="Summarize current browser context"/);
  assert.doesNotMatch(workspace, /from sidebar/);
  assert.doesNotMatch(workspace, /Open browser context status in sidebar/);
  for (const id of ["save-intake", "save-selection", "context-toggle", "dictate-button", "connection-line"]) {
    const button = workspace.match(new RegExp(`<button id="${id}"[\\s\\S]*?<\\/button>`))?.[0] ?? "";
    assert.match(button, /<svg /);
    assert.doesNotMatch(button.replace(/aria-label="[^"]*"/g, "").replace(/title="[^"]*"/g, ""), />\s*(Save|Status|Mic|Ready)\s*</i);
  }
  assert.doesNotMatch(workspace, /mode-select/);
  assert.doesNotMatch(workspace, /Open Sidebar/);
  assert.doesNotMatch(workspace, /id="open-sidebar"/);
  assert.match(workspace, /main-workspace\.js/);
  assert.match(workspaceScript, /createChatSessionStore/);
  assert.match(workspaceScript, /renderRailNavigation/);
  assert.match(workspaceScript, /starterPromptsHidden/);
  assert.match(workspaceScript, /augmentorStarterPromptsHidden/);
  assert.match(workspaceScript, /starterPrompts\.slice\(0, 6\)/);
  assert.match(workspaceScript, /Hide suggestions/);
  assert.match(workspaceScript, /Show suggestions/);
  assert.match(workspaceScript, /starter-prompt-grid/);
  assert.doesNotMatch(workspaceScript, /data-workspace-command/);
  assert.match(workspaceScript, /railSearchMatchesProject/);
  assert.match(workspaceScript, /railSearchMatchesSession/);
  assert.match(workspaceRail, /railSearchMatchesProject/);
  assert.match(workspaceRail, /railSearchMatchesSession/);
  assert.match(workspaceScript, /chatSessionStore\.getSessions/);
  assert.match(workspaceScript, /chatSessionStore\.getProjects/);
  assert.match(workspaceScript, /chatSessionStore\.switchSession/);
  assert.match(workspaceScript, /setSessionPinned/);
  assert.match(workspaceScript, /setSessionArchived/);
  assert.match(workspaceScript, /renameSession/);
  assert.match(workspaceScript, /setSessionProject/);
  assert.match(workspaceScript, /createProject/);
  assert.match(workspaceScript, /renameProject/);
  assert.match(workspaceScript, /setProjectArchived/);
  assert.match(workspaceScript, /setProjectExpanded/);
  assert.match(workspaceScript, /deleteSessionFromRail/);
  assert.match(workspaceScript, /forkSession/);
  assert.match(workspaceScript, /orderedRailItems/);
  assert.match(workspaceScript, /!session\.projectId/);
  assert.match(workspaceScript, /rail-project-chat-list/);
  assert.match(workspaceScript, /rail-unread-dot/);
  assert.match(workspaceScript, /railProjectActions/);
  assert.match(workspaceScript, /aria-expanded/);
  assert.match(workspaceScript, /Collapse.*project/);
  assert.match(workspaceScript, /Open chat:/);
  assert.match(workspaceScript, /aria-current", "true"/);
  assert.match(workspaceScript, /dragstart/);
  assert.match(workspaceScript, /drop/);
  assert.match(workspaceScript, /createComposerController\(\{\s*commandForm,\s*commandInput,\s*forceClipboardFallback: true,/);
  assert.match(workspaceScript, /hydrateProviderModelOptions/);
  assert.match(workspaceScript, /createDictationController/);
  assert.match(workspaceScript, /activeChatAbortController/);
  assert.match(workspaceScript, /createBrowserPageActions/);
  assert.match(workspaceScript, /fileLooksTextLike/);
  assert.match(workspaceScript, /removeAttachment/);
  assert.match(workspaceScript, /renderArtifactsWorkspace/);
  assert.match(workspaceScript, /renderAddOnsWorkspace/);
  assert.match(workspaceScript, /continueFromArtifact/);
  assert.doesNotMatch(workspaceScript, /renderChatHistory/);
  assert.doesNotMatch(workspaceScript, /historyActionButton/);
  assert.match(workspaceScript, /setActiveSessionWorkspace/);
  assert.match(workspaceScript, /\/augmentor\/chat/);
  assert.match(workspaceScript, /response\?\.reply/);
  assert.match(workspaceScript, /planMainWorkspacePrompt/);
  assert.match(promptRouter, /parseAutonomousBrowserActionIntent/);
  assert.match(promptRouter, /parseNaturalBrowserIntent/);
  assert.match(promptRouter, /parseNaturalDelegationIntent/);
  assert.match(workspaceScript, /augmentorPendingSidebarPrompt/);
  assert.match(workspaceScript, /handoffSidebarPrompt/);
  assert.match(workspaceScript, /open_side_panel/);
  assert.match(workspaceScript, /type: "open_side_panel",\s*force: true/);
  assert.match(workspaceScript, /suppressSidebarChatForMainWorkspace/);
  assert.match(workspaceScript, /suppress_side_panel_on_main_workspace/);
  assert.doesNotMatch(workspaceScript, /openSidebarButton/);
  assert.match(workspaceScript, /chrome\.tabs\.update/);
  assert.match(workspaceScript, /composerController\.bind\(\)/);
  assert.match(workspaceScript, /connectionLine\.innerHTML/);
  assert.match(workspaceScript, /readPageButton\?\.addEventListener\("click", \(\) => void browserPageActions\.readActivePage\(\)\)/);
  assert.match(workspaceScript, /saveIntakeButton\?\.addEventListener\("click", \(\) => void browserPageActions\.saveCurrentPageToArchive\(\)\)/);
  assert.match(workspaceScript, /saveSelectionButton\?\.addEventListener\("click", \(\) => void browserPageActions\.saveSelectionToArchive\(\)\)/);
  assert.match(workspaceScript, /contextToggleButton\?\.addEventListener\("click", \(\) => void browserPageActions\.summarizeSnapshot\(\)\)/);
  assert.match(workspace, /context-popover/);
  assert.match(workspaceScript, /contextMeter\?\.addEventListener\("click", toggleContextPopover\)/);
  assert.match(workspaceScript, /renderContextMemoryPopover/);
  assert.doesNotMatch(workspaceScript, /await addMessage\(\s*"system",\s*\[\s*"Context usage"/);
  assert.match(workspaceScript, /renderHermesWorkspace/);
  assert.match(workspaceScript, /renderOpenCodeWorkspace/);
  assert.match(workspaceScript, /renderSettingsWorkspace/);
  assert.match(workspaceSettings, /renderPrivacySection/);
  assert.match(workspaceSettings, /renderAboutSection/);
  assert.match(workspaceSettings, /label: "Privacy"/);
  assert.match(workspaceSettings, /label: "About"/);
  assert.match(aboutSettings, /ResonantOS Browser Layer/);
  assert.match(aboutSettings, /Customize Chromium/);
  assert.match(aboutSettings, /chrome:\/\/settings\/appearance/);
  assert.match(aboutSettings, /chrome:\/\/extensions\/\?id=/);
  assert.match(browserControlSettings, /Native browser surfaces/);
  assert.match(browserControlSettings, /Recent downloads/);
  assert.match(browserControlSettings, /\/browser\/downloads/);
  assert.match(browserControlSettings, /\/browser\/downloads\/action/);
  assert.match(browserControlSettings, /browser-download-action/);
  assert.match(browserControlSettings, /Clear Download History/);
  assert.match(browserControlSettings, /label: "Open"/);
  assert.match(browserControlSettings, /label: "Reveal"/);
  assert.match(browserControlSettings, /chrome:\/\/downloads/);
  assert.match(browserControlSettings, /chrome:\/\/settings\/content/);
  assert.match(diagnosticsSettings, /diagnostics-report-export/);
  assert.match(workspaceScript, /document\.body\.dataset\.workspace/);
  assert.match(workspaceScript, /\/addons\/status/);
  assert.match(workspaceScript, /\/hermes\/dashboard\/status/);
  assert.match(workspaceScript, /\/hermes\/dashboard\/start/);
  assert.match(workspaceScript, /\/hermes\/dashboard\/stop/);
  assert.match(workspaceScript, /\/addons\/delegate/);
  assert.match(commandRouter, /name === "email"/);
  assert.match(commandRouter, /name === "calendar"/);
  assert.match(appCommandHandlers, /parseDraftAddonCommand/);
  assert.match(appCommandHandlers, /\/addons\/draft/);
  assert.match(appCommandHandlers, /Sending email/);
  assert.match(appCommandHandlers, /Scheduling calendar events/);
  assert.match(workspaceScript, /target: "hermes"/);
  assert.match(promptRouter, /parseHermesSlashCommand/);
  assert.match(promptRouter, /parseMemorySlashCommand/);
  assert.match(promptRouter, /parseOpenCodeSlashCommand/);
  assert.match(workspaceScript, /parseDraftAddonCommand/);
  assert.match(promptRouter, /parseDraftSlashCommand/);
  assert.match(promptRouter, /parseWalletSlashCommand/);
  assert.match(promptRouter, /parseDaoSlashCommand/);
  assert.match(workspaceScript, /runMemoryCommand/);
  assert.match(workspaceScript, /detectWalletState/);
  assert.match(workspaceScript, /prepareDaoWorkflowGuidance/);
  assert.match(workspaceScript, /runOpenCodeCommand/);
  assert.match(workspaceScript, /runDraftAddonCommand/);
  assert.match(workspaceScript, /\/addons\/draft/);
  assert.match(workspaceScript, /onOpenProviderHandoff/);
  assert.match(workspaceScript, /chrome\.tabs\.create/);
  assert.match(workspaceScript, /pendingWorkspaceAction/);
  assert.match(workspaceScript, /AI browser workspace/);
  assert.match(workspaceScript, /Read this page/);
  assert.match(workspaceScript, /Search AI memory/);
  assert.match(workspaceScript, /Send to Hermes/);
  assert.match(workspaceScript, /commandInput\.value = button\.dataset\.prompt/);
  assert.match(workspaceScript, /iframe\.src = dashboard\.url/);
  assert.match(workspaceScript, /augmentorMainWorkspace/);
  assert.match(workspaceScript, /hydrateActiveWorkspace/);
  assert.match(workspaceScript, /createSidePanelRenderers/);
  assert.match(workspaceScript, /chatRenderers\.renderMessages/);
  assert.match(workspaceScript, /chatRenderers\.renderAttachments/);
  assert.match(workspaceScript, /renderEmptyState/);
  assert.doesNotMatch(workspaceScript, /messageActionButton/);
  assert.match(workspaceScript, /copyMessage/);
  assert.match(workspaceScript, /forkFromMessage/);
  assert.match(workspaceScript, /deleteMessage/);
  assert.match(workspaceScript, /editMessage/);
  assert.match(workspaceScript, /saveMessageToArchive/);
  assert.match(workspaceScript, /regenerateFromMessage/);
  assert.match(workspaceScript, /setActiveWorkspace\("hermes"/);
  assert.match(workspaceStyles, /message-actions/);
  assert.match(workspaceStyles, /message-action/);
  assert.match(workspaceStyles, /conic-gradient\(var\(--accent\) var\(--context-used/);
  assert.match(workspaceStyles, /workspace-shell/);
  assert.match(workspaceStyles, /starter-prompt-grid/);
  assert.match(workspaceStyles, /min-height: 72px/);
  assert.match(workspaceStyles, /starter-prompt-controls/);
  assert.match(workspaceStyles, /hero-kicker/);
  assert.match(workspaceStyles, /answer-workspace/);
  assert.match(workspaceStyles, /artifacts-workspace/);
  assert.match(workspaceStyles, /addons-workspace/);
  assert.match(workspaceStyles, /addon-card/);
  assert.match(workspaceStyles, /addon-draft-review/);
  assert.match(workspaceStyles, /addon-draft-card/);
  assert.match(workspaceStyles, /artifact-preview/);
  assert.match(workspaceStyles, /artifact-actions/);
  assert.match(workspaceStyles, /artifact-insights/);
  assert.match(workspaceStyles, /artifact-row-guidance/);
  assert.match(launcher, /artifactInsights/);
  assert.match(workspaceStyles, /module-workspace/);
  assert.match(workspaceStyles, /dashboard-frame-card/);
  assert.match(workspaceStyles, /settings-workspace/);
  assert.match(workspaceStyles, /settings-provider-card/);
  assert.match(workspaceStyles, /memory-review-queue/);
  assert.match(workspaceStyles, /memory-review-actions/);
  assert.match(workspaceStyles, /memory-review-draft/);
  assert.match(workspaceStyles, /memory-review-preview/);
  assert.match(workspaceStyles, /memory-promotion-history/);
  assert.match(workspaceStyles, /memory-promotion-card/);
  assert.match(launcher, /defaultMainWorkspaceUrl/);
  assert.match(launcher, /clearResonantNewTabOverride/);
  assert.match(launcher, /chrome_url_overrides/);
  assert.match(launcher, /\/hermes\/dashboard\/status/);
  assert.match(launcher, /\/hermes\/dashboard\/start/);
  assert.match(launcher, /\/hermes\/dashboard\/stop/);
  assert.match(launcher, /executeAddonDraftList/);
  assert.match(launcher, /executeAddonDraftTransition/);
  assert.match(launcher, /\/addons\/draft\/list/);
  assert.match(launcher, /\/addons\/draft\/transition/);
  assert.match(launcher, /\/addons\/draft\/handoff/);
  assert.match(launcher, /executeAddonDraftProviderHandoff/);
  assert.match(launcher, /buildProviderDraftHandoff/);
  assert.match(launcher, /\/opencode\/status/);
  assert.match(launcher, /\/providers\/status/);
  assert.match(launcher, /\/providers\/credentials/);
  assert.match(launcher, /\/providers\/accounts/);
  assert.match(launcher, /\/providers\/routing-strategies/);
  assert.match(launcher, /provider-routing-write/);
  assert.match(launcher, /provider-credential-write/);
  assert.match(launcher, /defaultRoutingStrategies/);
  assert.match(launcher, /\/diagnostics\/report/);
  assert.match(launcher, /diagnostics-report-export/);
  assert.match(launcher, /executeDiagnosticsReport/);
  assert.match(launcher, /\/browser\/downloads/);
  assert.match(launcher, /\/browser\/downloads\/action/);
  assert.match(launcher, /executeBrowserDownloads/);
  assert.match(launcher, /executeBrowserDownloadAction/);
  assert.match(launcher, /browserDownloadsRoot/);
  assert.match(launcher, /browser-download-action/);
  assert.match(launcher, /clear-history/);
  assert.match(launcher, /openOrRevealDownload/);
  assert.match(launcher, /\/archive\/intake\/list/);
  assert.match(launcher, /\/memory\/settings/);
  assert.match(launcher, /memory-settings-write/);
  assert.match(launcher, /\/memory\/source\/browse/);
  assert.match(launcher, /memory-source-browse/);
  assert.match(launcher, /\/memory\/source\/scan/);
  assert.match(launcher, /memory-source-scan/);
  assert.match(launcher, /\/memory\/source\/action/);
  assert.match(launcher, /memory-source-manage/);
  assert.match(launcher, /\/memory\/source\/review/);
  assert.match(launcher, /memory-source-review/);
  assert.match(launcher, /\/memory\/source\/intake/);
  assert.match(launcher, /memory-source-intake/);
  assert.match(launcher, /\/memory\/source\/file-intake/);
  assert.match(launcher, /\/memory\/wiki\/health/);
  assert.match(launcher, /computeWikiHealth/);
  assert.match(launcher, /sourceContentHash/);
  assert.match(launcher, /sourceVersion/);
  assert.match(launcher, /\/memory\/source\/versions/);
  assert.match(launcher, /\/memory\/source\/diff/);
  assert.match(launcher, /memory-source-file-intake/);
  assert.match(launcher, /RESONANTOS_BROWSER_FIRST_PICK_FOLDER_RESULT/);
  assert.match(launcher, /\/archive\/intake\/read/);
  assert.match(launcher, /\/archive\/review\/request/);
  assert.match(launcher, /\/archive\/review\/list/);
  assert.match(launcher, /\/archive\/review\/transition/);
  assert.match(launcher, /\/archive\/review\/draft/);
  assert.match(launcher, /\/archive\/review\/artifact\/read/);
  assert.match(launcher, /\/archive\/review\/artifact\/verify/);
  assert.match(launcher, /\/archive\/review\/verification\/read/);
  assert.match(launcher, /\/archive\/review\/artifact\/revise/);
  assert.match(launcher, /draftVerificationStatus/);
  assert.match(launcher, /promotionStatus/);
  assert.match(launcher, /providerRouteForArchiveVerifier/);
  assert.match(launcher, /runArchiveSemanticVerifier/);
  assert.match(launcher, /semanticVerifierStatus/);
  assert.match(launcher, /\/archive\/review\/artifact\/promote/);
  assert.match(launcher, /\/archive\/review\/promotions\/list/);
  assert.match(launcher, /\/archive\/review\/promotions\/restore/);
  assert.match(archiveMerge, /mergePromotedMarkdownBody/);
  assert.match(archiveMerge, /Superseded Sections/);
  assert.match(launcher, /executeProviderCredentialSave/);
  assert.match(launcher, /executeOpenCodeStatus/);
  assert.match(launcher, /workspaceLaunch: "not-enabled-in-browser-first-v1"/);
  assert.match(launcher, /Hermes dashboard can only bind to localhost/);
  assert.match(launcher, /main-workspace\.html/);
  assert.match(background, /open_side_panel/);
  assert.match(background, /suppress_side_panel_on_main_workspace/);
  assert.match(background, /openResonantSidePanel\(windowId, \{ force: Boolean\(message\.force\) \}\)/);
  assert.match(background, /setSidePanelEnabledForTab\(tab\.id, false\)/);
  assert.match(sidePanel, /consumePendingSidebarPrompt/);
  assert.match(sidePanel, /chrome\.storage\?\.onChanged/);
  assert.doesNotMatch(background, /onInstalled[\s\S]*setTimeout/);
});

test("browser layer has a human approval boundary for wallet and credential actions", async () => {
  const background = await readText(path.join(extensionRoot, "src", "background.js"));
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.html"));
  const script = await readText(path.join(extensionRoot, "src", "side-panel.js"));

  assert.match(background, /wallet_connect/);
  assert.match(background, /wallet_sign/);
  assert.match(background, /credential_autofill/);
  assert.match(background, /deniedToAutomation/);
  assert.match(panel, /Message Augmentor/);
  assert.match(script, /Wallet actions are human-approval gated/);
});

test("browser layer exposes Augmentor chat as the side-panel surface without stealing the browser tab", async () => {
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.html"));
  const script = await readText(path.join(extensionRoot, "src", "side-panel.js"));
  const appCommandHandlers = await readText(path.join(extensionRoot, "src", "lib", "app-command-handlers.js"));
  const bridgeClient = await readText(path.join(extensionRoot, "src", "lib", "bridge-client.js"));
  const commandParser = await readText(path.join(extensionRoot, "src", "lib", "browser-command-parser.js"));
  const browserJobStore = await readText(path.join(extensionRoot, "src", "lib", "browser-job-store.js"));
  const chatTurnController = await readText(path.join(extensionRoot, "src", "lib", "chat-turn-controller.js"));
  const composerController = await readText(path.join(extensionRoot, "src", "lib", "composer-controller.js"));
  const controlPageObserver = await readText(path.join(extensionRoot, "src", "lib", "control-page-observer.js"));
  const controlPlanningService = await readText(path.join(extensionRoot, "src", "lib", "control-planning-service.js"));
  const controlPreflight = await readText(path.join(extensionRoot, "src", "lib", "control-preflight.js"));
  const controlReportingService = await readText(path.join(extensionRoot, "src", "lib", "control-reporting-service.js"));
  const controlRunState = await readText(path.join(extensionRoot, "src", "lib", "control-run-state.js"));
  const controlStepExecutor = await readText(path.join(extensionRoot, "src", "lib", "control-step-executor.js"));
  const approvalPolicy = await readText(path.join(extensionRoot, "src", "lib", "approval-policy.js"));
  const agentControlPlanner = await readText(path.join(extensionRoot, "src", "lib", "agent-control-planner.js"));
  const agentControlRunner = await readText(path.join(extensionRoot, "src", "lib", "agent-control-runner.js"));
  const pageActions = await readText(path.join(extensionRoot, "src", "lib", "browser-page-actions.js"));
  const chatSessionStore = await readText(path.join(extensionRoot, "src", "lib", "chat-session-store.js"));
  const messageActionController = await readText(path.join(extensionRoot, "src", "lib", "message-action-controller.js"));
  const sidePanelRenderers = await readText(path.join(extensionRoot, "src", "lib", "side-panel-renderers.js"));
  const monitorRenderers = await readText(path.join(extensionRoot, "src", "lib", "monitor-renderers.js"));
  const commandRouter = await readText(path.join(extensionRoot, "src", "lib", "side-panel-command-router.js"));
  const walletState = await readText(path.join(extensionRoot, "src", "lib", "wallet-state.js"));
  const sitePermissionStore = await readText(path.join(extensionRoot, "src", "lib", "site-permission-store.js"));
  const taskConsentStore = await readText(path.join(extensionRoot, "src", "lib", "task-consent-store.js"));
  const tabContextController = await readText(path.join(extensionRoot, "src", "lib", "tab-context-controller.js"));
  const background = await readText(path.join(extensionRoot, "src", "background.js"));

  assert.match(panel, /Message Augmentor/);
  assert.doesNotMatch(panel, /new-chat/);
  assert.doesNotMatch(panel, /chat-history/);
  assert.match(panel, /bridge-config\.generated\.js/);
  assert.match(panel, /control-monitor/);
  assert.match(panel, /control-current-action/);
  assert.match(panel, /control-stop/);
  assert.match(panel, /context-dock"[^>]+hidden/);
  assert.match(panel, /context-toggle/);
  assert.match(panel, /approval-card/);
  assert.match(panel, /approval-trust-site/);
  assert.match(panel, /site-permission-panel/);
  assert.match(panel, /task-consent-panel/);
  assert.match(panel, /permission-manager-panel/);
  assert.match(panel, /Permission and consent manager/);
  assert.match(panel, /Trust this task class/);
  assert.match(panel, /job-monitor/);
  assert.match(panel, /control-preflight-card/);
  assert.match(panel, /control-preflight-approve/);
  assert.match(panel, /control-preflight-trust/);
  assert.match(panel, /control-preflight-deny/);
  assert.match(panel, /trusted-for-safe-actions/);
  assert.doesNotMatch(panel, /I.m here in the browser side bar/);
  assert.doesNotMatch(panel, /Current page/);
  assert.match(panel, /Connected model/);
  assert.match(panel, /Thinking depth/);
  assert.match(panel, /Save current page to Living Archive intake/);
  assert.match(panel, /Save selected page text to Living Archive intake/);
  assert.match(panel, /context-meter-label/);
  for (const id of ["save-intake", "save-selection", "context-toggle", "dictate-button", "connection-line"]) {
    const button = panel.match(new RegExp(`<button id="${id}"[\\s\\S]*?<\\/button>`))?.[0] ?? "";
    assert.match(button, /<svg /);
    assert.doesNotMatch(button.replace(/aria-label="[^"]*"/g, "").replace(/title="[^"]*"/g, ""), />\s*(Save|Status|Mic|Ready)\s*</i);
  }
  assert.match(script, /createComposerController\(\{\s*commandForm,\s*commandInput,\s*forceClipboardFallback: true,/);
  assert.match(script, /hydrateProviderModelOptions/);
  assert.match(script, /createDictationController/);
  assert.match(script, /stopChatTurn/);
  assert.match(panel, /context-popover/);
  assert.match(script, /contextMeter\.addEventListener\("click", toggleContextPopover\)/);
  assert.match(script, /renderContextMemoryPopover/);
  assert.doesNotMatch(script, /await addMessage\(\s*"system",\s*\[\s*"Context usage"/);
  assert.match(composerController, /shortcutKey === "z"/);
  assert.match(composerController, /shortcutKey === "a"/);
  assert.match(composerController, /\["x", "c", "v"\]/);
  assert.match(background, /openPanelOnActionClick/);
  assert.match(background, /openResonantSidePanel/);
  assert.match(background, /open-augmentor-side-panel/);
  assert.doesNotMatch(background, /chrome\.tabs\.create/);
  assert.match(background, /syncSidePanelForTab/);
  assert.match(background, /chrome\.tabs\.onActivated/);
  assert.match(background, /chrome\.tabs\.onUpdated/);
  assert.match(background, /isMainWorkspaceUrl\(tab\.url\) && !force/);
  assert.match(background, /setSidePanelEnabledForTab\(tab\.id, false\)/);
  assert.match(script, /isReadableBrowserTab/);
  assert.match(pageActions, /currentWindow: true/);
  assert.match(pageActions, /summarizeSnapshot/);
  assert.match(pageActions, /saveCurrentPageToArchive/);
  assert.match(pageActions, /saveSelectionToArchive/);
  assert.match(pageActions, /\/archive\/review\/request/);
  assert.match(script, /saveIntake/);
  assert.match(script, /createChatSessionStore/);
  assert.doesNotMatch(script, /renderChatHistory/);
  assert.doesNotMatch(script, /chatHistory/);
  assert.doesNotMatch(script, /newChatButton/);
  assert.match(script, /createChatTurnController/);
  assert.match(chatTurnController, /\/augmentor\/chat/);
  assert.match(chatTurnController, /pageContextForSnapshot/);
  assert.match(chatTurnController, /runtimeContextForAttachments/);
  assert.match(chatTurnController, /providerMessagesFromHistory/);
  assert.match(script, /createComposerController\(\{\s*commandForm,\s*commandInput,\s*forceClipboardFallback: true,/);
  assert.match(script, /connectionLine\.innerHTML/);
  assert.match(script, /connectionLine\.setAttribute\("aria-label", connectionLine\.title\)/);
  assert.doesNotMatch(panel, /<span>Ready<\/span>/);
  assert.match(composerController, /handleClipboardShortcut/);
  assert.match(composerController, /selectedRange/);
  assert.match(composerController, /replaceSelection/);
  assert.match(composerController, /clipboard\?\.readText/);
  assert.match(composerController, /clipboard\?\.writeText/);
  assert.match(composerController, /resetUndoStack/);
  assert.match(composerController, /requestSubmit/);
  assert.match(script, /createMessageActionController/);
  assert.match(messageActionController, /copyMessage/);
  assert.match(messageActionController, /forkFromMessage/);
  assert.match(messageActionController, /saveMessageToArchive/);
  assert.match(messageActionController, /regenerateFromMessage/);
  assert.match(messageActionController, /attachFiles/);
  assert.match(chatSessionStore, /forkFromMessage/);
  assert.match(chatSessionStore, /createSession/);
  assert.match(chatSessionStore, /switchSession/);
  assert.match(chatSessionStore, /getSessions/);
  assert.match(chatSessionStore, /trimToPreviousUserMessage/);
  assert.match(chatSessionStore, /addAttachments/);
  assert.match(chatSessionStore, /hydrate/);
  assert.match(script, /createSidePanelRenderers/);
  assert.match(script, /createAppCommandHandlers/);
  assert.match(appCommandHandlers, /parseHistorySearchCommand/);
  assert.match(appCommandHandlers, /formatHistorySearchMarkdown/);
  assert.match(appCommandHandlers, /browser-history-search/);
  assert.match(appCommandHandlers, /runGoalCommand/);
  assert.match(appCommandHandlers, /runSitePermissionCommand/);
  assert.match(appCommandHandlers, /runJobsCommand/);
  assert.match(appCommandHandlers, /pauseBrowserJob/);
  assert.match(appCommandHandlers, /runWalletStatusCommand/);
  assert.match(commandRouter, /name === "wallet"/);
  assert.match(commandRouter, /name === "dao"/);
  assert.match(pageActions, /detectWalletState/);
  assert.match(pageActions, /prepareDaoWorkflowGuidance/);
  assert.match(pageActions, /saveWalletDaoAuditToArchive/);
  assert.match(pageActions, /browser-wallet-dao-audit/);
  assert.match(commandRouter, /saveWalletDaoAuditToArchive/);
  assert.match(commandRouter, /\^audit\\b/);
  assert.match(pageActions, /world: "MAIN"/);
  assert.match(walletState, /detectionOnly/);
  assert.match(walletState, /read-only detection/);
  assert.match(script, /createSidePanelCommandRouter/);
  assert.match(commandRouter, /respondToCommand/);
  assert.match(commandRouter, /name === "hermes"/);
  assert.match(commandRouter, /parseControlIntent/);
  assert.match(commandRouter, /handleWalletBoundary/);
  assert.match(sidePanelRenderers, /renderMessages/);
  assert.match(sidePanelRenderers, /What should Augmentor work on/);
  assert.match(sidePanelRenderers, /renderAttachments/);
  assert.match(sidePanelRenderers, /flashCopied/);
  assert.match(script, /createSitePermissionStore/);
  assert.match(sitePermissionStore, /siteKeyForUrl/);
  assert.match(sitePermissionStore, /permissionForUrl/);
  assert.match(sitePermissionStore, /resetSitePermission/);
  assert.match(sitePermissionStore, /setSitePermission/);
  assert.match(sitePermissionStore, /sitePermissionAudit/);
  assert.match(sitePermissionStore, /ask-before-action/);
  assert.match(taskConsentStore, /taskClassForGoal/);
  assert.match(taskConsentStore, /taskConsentKey/);
  assert.match(taskConsentStore, /taskConsentAudit/);
  assert.match(script, /createTaskConsentStore/);
  assert.match(script, /augmentorSitePermissionAudit/);
  assert.match(script, /augmentorTaskConsents/);
  assert.match(script, /augmentorTaskConsentAudit/);
  assert.match(monitorRenderers, /renderTaskConsentPanel/);
  assert.match(monitorRenderers, /renderPermissionManager/);
  assert.match(monitorRenderers, /auditLabel/);
  assert.match(monitorRenderers, /onResetSitePermission/);
  assert.match(monitorRenderers, /onRevokeTaskConsent/);
  assert.match(script, /createMonitorRenderers/);
  assert.match(monitorRenderers, /sitePermissionDescription/);
  assert.match(monitorRenderers, /Can see\/do now/);
  assert.match(monitorRenderers, /renderSitePermissionPanel/);
  assert.match(monitorRenderers, /renderJobMonitor/);
  assert.match(monitorRenderers, /getBrowserJobSchedulerState/);
  assert.match(monitorRenderers, /job-scheduler-state/);
  assert.match(monitorRenderers, /renderControlMonitor/);
  assert.match(monitorRenderers, /controlActionStateLabel/);
  assert.match(monitorRenderers, /controlRunPhase/);
  assert.match(monitorRenderers, /controlRunProgressSummary/);
  assert.match(monitorRenderers, /control-phase-meta/);
  assert.match(monitorRenderers, /control-progress-track/);
  assert.match(monitorRenderers, /jobNextHumanAction/);
  assert.match(monitorRenderers, /job-blocker-guidance/);
  assert.match(monitorRenderers, /job-progress/);
  assert.match(script, /controlStopButton\.addEventListener/);
  assert.match(script, /createTabContextController/);
  assert.match(tabContextController, /resolveTabMention/);
  assert.match(tabContextController, /bindMentionedTab/);
  assert.match(tabContextController, /consumeInlineDraft/);
  assert.match(tabContextController, /bindBrowserListeners/);
  assert.match(tabContextController, /hydrateInitialContext/);
  assert.match(script, /createBridgeClient/);
  assert.match(bridgeClient, /bridgeUrl = config\.bridgeUrl \?\? "http:\/\/127\.0\.0\.1:47773"/);
  assert.match(bridgeClient, /__RESONANTOS_BRIDGE_CONFIG__/);
  assert.match(bridgeClient, /X-ResonantOS-Bridge-Token/);
  assert.match(script, /browserJobStore\.getMonitorCollapsed/);
  assert.match(script, /browserJobStore\.getSchedulerState/);
  assert.match(chatTurnController, /\/augmentor\/chat/);
  assert.match(controlReportingService, /\/archive\/intake/);
  assert.match(appCommandHandlers, /\/memory\/search/);
  assert.match(appCommandHandlers, /\/addons\/delegate/);
  assert.match(appCommandHandlers, /\/goals/);
  assert.match(commandParser, /parseNaturalBrowserIntent/);
  assert.match(script, /createBrowserJobStore/);
  assert.match(script, /prepareBrowserJobPageLock/);
  assert.match(script, /conflictingActiveJobForLock/);
  assert.match(script, /TERMINAL_CONTROL_RUN_STATUSES/);
  assert.match(script, /conflict && currentControlRun && conflict\.id === currentControlRun\.id/);
  assert.match(script, /conflict\?\.status === "approval"/);
  assert.match(script, /pendingApproval = null/);
  assert.match(browserJobStore, /normalizeBrowserJob/);
  assert.match(browserJobStore, /normalizePageLock/);
  assert.match(browserJobStore, /browserJobSchedulerState/);
  assert.match(browserJobStore, /createBrowserJobStore/);
  assert.match(browserJobStore, /LOCK_HOLDING_JOB_STATUSES/);
  assert.match(browserJobStore, /conflictingActiveJobForLock/);
  assert.match(browserJobStore, /Browser target is already controlled/);
  assert.match(browserJobStore, /toggleMonitorCollapsed/);
  assert.match(browserJobStore, /findJob/);
  assert.match(browserJobStore, /getSchedulerState/);
  assert.match(browserJobStore, /steps/);
  assert.match(commandParser, /parseNaturalSearchIntent/);
  assert.match(commandParser, /parseTypeIntent/);
  assert.match(commandParser, /parseClickIntent/);
  assert.match(commandParser, /parseReadPageIntent/);
  assert.match(commandParser, /parseStructuredPageEditIntent/);
  assert.match(commandParser, /parseScrollIntent/);
  assert.match(commandParser, /parseFormsIntent/);
  assert.match(commandParser, /parseControlIntent/);
  assert.match(commandParser, /parseAutonomousBrowserActionIntent/);
  assert.match(commandParser, /parseAmazonShoppingTask/);
  assert.match(appCommandHandlers, /runHistorySearchCommand/);
  assert.match(appCommandHandlers, /Incognito activity is excluded/);
  assert.match(appCommandHandlers, /chrome\.tabs\.query/);
  assert.match(appCommandHandlers, /runSitePermissionCommand/);
  assert.match(appCommandHandlers, /runCapabilitiesCommand/);
  assert.match(script, /approvalBoundaryForStep/);
  assert.match(script, /controlStepLabel/);
  assert.match(agentControlPlanner, /planControlSteps/);
  assert.match(agentControlPlanner, /deterministicNextAction/);
  assert.match(agentControlPlanner, /dedupeControlSteps/);
  assert.match(agentControlPlanner, /controlStepLabel/);
  assert.match(script, /trustCurrentTaskForSafeActions/);
  assert.match(appCommandHandlers, /runJobsCommand/);
  assert.match(appCommandHandlers, /pauseBrowserJob/);
  assert.match(appCommandHandlers, /resumeBrowserJob/);
  assert.match(appCommandHandlers, /continueBrowserJob/);
  assert.match(appCommandHandlers, /Scheduler:/);
  assert.match(appCommandHandlers, /reportBrowserJob/);
  assert.match(appCommandHandlers, /cancelBrowserJob/);
  assert.match(commandRouter, /reportBrowserJob/);
  assert.match(commandRouter, /continueBrowserJob/);
  assert.match(script, /augmentorBrowserJobs/);
  assert.match(script, /augmentorActiveBrowserJob/);
  assert.match(script, /recoverInterruptedJobs/);
  assert.match(script, /renderSitePermissionPanel/);
  assert.match(script, /sitePermissionMode\.addEventListener/);
  assert.match(tabContextController, /resolveTabMention/);
  assert.match(tabContextController, /augmentorInlineDraft/);
  assert.match(pageActions, /searchBrowser/);
  assert.match(pageActions, /typeIntoActivePage/);
  assert.match(pageActions, /clickActivePageText/);
  assert.match(pageActions, /scrollActivePage/);
  assert.match(pageActions, /detectActivePageForms/);
  assert.match(script, /controlledTabId/);
  assert.match(controlStepExecutor, /switch_tab/);
  assert.match(agentControlPlanner, /List open tabs/);
  assert.match(agentControlPlanner, /planControlSteps/);
  assert.match(script, /createControlPlanningService/);
  assert.match(script, /createControlPreflight/);
  assert.match(script, /formatControlPreflightMessage/);
  assert.match(script, /augmentorControlPreflight/);
  assert.match(script, /renderControlPreflightCard/);
  assert.match(script, /approveControlPreflight/);
  assert.match(script, /trustControlPreflightForSafeActions/);
  assert.match(script, /setNextControlPreflightDecision/);
  assert.match(script, /consumeNextControlPreflightDecision/);
  assert.match(script, /preflightDecisionFromPreflight/);
  assert.match(script, /source: "control-preflight"/);
  assert.match(script, /denyControlPreflight/);
  assert.match(commandRouter, /approve-control/);
  assert.match(commandRouter, /deny-control/);
  assert.match(controlPreflight, /taskClassForGoal/);
  assert.match(controlPreflight, /Still human-only: wallet, login, credential, payment/);
  assert.match(controlPreflight, /shouldRequireControlPreflight/);
  assert.match(controlPlanningService, /requestControlPlan/);
  assert.match(controlPlanningService, /requestNextControlAction/);
  assert.match(agentControlRunner, /continueControlLoop/);
  assert.match(agentControlRunner, /browserJobStepHistory/);
  assert.match(agentControlRunner, /resumedFromJob/);
  assert.match(agentControlRunner, /existingJob: resumedFromJob/);
  assert.match(script, /activateJob\(existingJob\.id\)/);
  assert.match(agentControlRunner, /observe-act-verify-loop/);
  assert.match(script, /createControlPageObserver/);
  assert.match(controlPageObserver, /observeControlPage/);
  assert.match(controlPageObserver, /listReadableTabSnapshots/);
  assert.match(controlPageObserver, /Browser job is paused/);
  assert.match(controlPageObserver, /Browser job was cancelled/);
  assert.match(approvalPolicy, /sanitizePlannerStep/);
  assert.match(approvalPolicy, /sanitizeNextActionDecision/);
  assert.match(approvalPolicy, /sanitizePlannerPlan/);
  assert.match(approvalPolicy, /approvalBoundaryForStep/);
  assert.match(controlPlanningService, /planAgentControlSteps/);
  assert.match(controlPlanningService, /__resonantosControlPlannerOverride/);
  assert.match(controlPlanningService, /__resonantosNextActionOverride/);
  assert.match(script, /createControlStepExecutor/);
  assert.match(controlStepExecutor, /executeControlStep/);
  assert.match(controlStepExecutor, /listReadableTabs/);
  assert.match(controlStepExecutor, /Unknown control step/);
  assert.match(agentControlRunner, /runControlCommand/);
  assert.match(script, /renderControlMonitor/);
  assert.match(agentControlRunner, /approvePendingControlStep/);
  assert.match(agentControlRunner, /denyPendingControlStep/);
  assert.match(script, /createControlReportingService/);
  assert.match(controlReportingService, /buildControlReport/);
  assert.match(controlReportingService, /saveControlReportToArchive/);
  assert.match(controlReportingService, /saveBrowserJobReportToArchive/);
  assert.match(controlReportingService, /Preflight Decision/);
  assert.match(monitorRenderers, /job-preflight/);
  assert.match(monitorRenderers, /job-focused/);
  assert.match(monitorRenderers, /getActiveBrowserJobId/);
  assert.match(monitorRenderers, /onActivateBrowserJob/);
  assert.match(monitorRenderers, /onSaveBrowserJobReport/);
  assert.match(controlReportingService, /delegateControlIssue/);
  assert.match(controlReportingService, /Browser Agent Control Report/);
  assert.match(script, /createControlRunState/);
  assert.match(controlRunState, /startControlRun/);
  assert.match(controlRunState, /appendControlStep/);
  assert.match(controlRunState, /updateControlStep/);
  assert.match(controlRunState, /finishControlRun/);
  assert.match(controlRunState, /setPageControlOverlay/);
  assert.match(agentControlRunner, /Agent Control Mode started/);
  assert.match(script, /explainStructuredPageEditBoundary/);
  assert.match(pageActions, /bing\.com\/news\/search/);
  assert.match(pageActions, /\/web\/news/);
  assert.match(script, /turnBusy/);
  assert.match(script, /runBusyUiAction/);
  assert.match(script, /controlPreflightTrustButton\.addEventListener\("click", \(\) => void runBusyUiAction/);
  assert.match(script, /setActivity/);
  assert.match(pageActions, /openBrowserUrl/);
  assert.match(pageActions, /chrome\.tabs\.update/);
  assert.match(pageActions, /chrome\.tabs\.create/);
  assert.match(messageActionController, /copyMessage/);
  assert.match(sidePanelRenderers, /message-action/);
  assert.match(composerController, /commandInput\.addEventListener\("keydown"/);
  assert.match(composerController, /commandForm\.requestSubmit\(\)/);
  assert.match(composerController, /event\.metaKey/);
  assert.match(composerController, /undoInput/);
  assert.match(composerController, /shortcutKey === "z"/);
  assert.match(composerController, /shortcutKey === "a"/);
  assert.match(composerController, /"x", "c", "v"/);
  assert.match(messageActionController, /forkFromMessage/);
  assert.match(messageActionController, /editMessage/);
  assert.match(messageActionController, /saveMessageToArchive/);
  assert.match(messageActionController, /regenerateFromMessage/);
  assert.match(messageActionController, /deleteMessage/);
  assert.doesNotMatch(script, /Full LLM replies will come from/);
});

test("main workspace and side-panel chat composers expose the same core controls", async () => {
  const workspace = await readText(path.join(extensionRoot, "src", "main-workspace.html"));
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.html"));
  const coreComposerControls = [
    "attach-file",
    "read-page",
    "save-intake",
    "save-selection",
    "context-toggle",
    "model-select",
    "thinking-depth",
    "dictate-button",
    "connection-line",
    "context-meter"
  ];

  for (const id of coreComposerControls) {
    assert.match(workspace, new RegExp(`id="${id}"`), `main workspace missing ${id}`);
    assert.match(panel, new RegExp(`id="${id}"`), `side panel missing ${id}`);
  }
  assert.match(workspace, /value="__auto__">Auto route/);
  assert.match(panel, /value="__auto__">Auto route/);

  for (const id of ["save-intake", "save-selection", "context-toggle", "dictate-button", "connection-line"]) {
    const workspaceControl = workspace.match(new RegExp(`<button id="${id}"[\\s\\S]*?<\\/button>`))?.[0] ?? "";
    const panelControl = panel.match(new RegExp(`<button id="${id}"[\\s\\S]*?<\\/button>`))?.[0] ?? "";
    assert.match(workspaceControl, /<svg /, `main workspace ${id} must be icon-only`);
    assert.match(panelControl, /<svg /, `side panel ${id} must be icon-only`);
    assert.doesNotMatch(workspaceControl.replace(/aria-label="[^"]*"/g, "").replace(/title="[^"]*"/g, ""), />\s*(Save|Status|Mic|Ready)\s*</i);
    assert.doesNotMatch(panelControl.replace(/aria-label="[^"]*"/g, "").replace(/title="[^"]*"/g, ""), />\s*(Save|Status|Mic|Ready)\s*</i);
  }
});

test("browser layer can read active tab context without raw privileged access", async () => {
  const content = await readText(path.join(extensionRoot, "src", "content.js"));
  const panel = await readText(path.join(extensionRoot, "src", "side-panel.js"));
  const pageActions = await readText(path.join(extensionRoot, "src", "lib", "browser-page-actions.js"));

  assert.match(content, /read_page/);
  assert.match(content, /click_text/);
  assert.match(content, /type_text/);
  assert.match(content, /resonantos-control-overlay/);
  assert.match(content, /control_overlay/);
  assert.match(content, /controlPhaseDetails/);
  assert.match(content, /ros-control-status-text/);
  assert.match(content, /ros-control-stop-button/);
  assert.match(content, /cancel_control_run/);
  assert.match(content, /Reading page\.\.\./);
  assert.match(content, /Typing\.\.\./);
  assert.match(content, /Taking screenshot\.\.\.|Clicking\.\.\.|Working\.\.\./);
  assert.match(content, /setControlSessionOverlay/);
  assert.match(content, /isTopWindow/);
  assert.match(content, /phase: message\.phase/);
  assert.match(content, /data-session="active"/);
  assert.match(content, /pulseControlOverlay/);
  assert.match(content, /resonantos-control-target/);
  assert.match(content, /resonantos-control-bubble/);
  assert.match(content, /showControlActionBubble/);
  assert.match(content, /userApproved/);
  assert.match(content, /isHardRestrictedElement/);
  assert.match(content, /scroll_page/);
  assert.match(content, /detect_forms/);
  assert.match(content, /clickVisibleText/);
  assert.match(content, /typeIntoPage/);
  assert.match(content, /scrollPage/);
  assert.match(content, /describeForms/);
  assert.match(content, /controls: candidateClickElements/);
  assert.match(content, /data-resonantos-control-ref/);
  assert.match(content, /resonantos-inline-assistant/);
  assert.match(content, /ros-inline-prompt/);
  assert.match(content, /inlineActionList/);
  assert.match(content, /inlineActionByShortcut/);
  assert.match(content, /editableSelectionDetails/);
  assert.match(content, /setRangeText/);
  assert.match(content, /insertReplacementText/);
  assert.match(content, /currentSitePermission/);
  assert.match(content, /augmentorInlineDraft/);
  assert.match(content, /ensureControlRef/);
  assert.match(content, /clickControlRef/);
  assert.match(content, /classifyEditableField/);
  assert.match(content, /search-query/);
  assert.match(content, /document-edit/);
  assert.match(content, /personal-contact/);
  assert.match(content, /Credential fields are human-only/);
  assert.match(content, /Payment and wallet fields are human-only/);
  assert.match(content, /safeToSubmit/);
  assert.match(content, /fields: Array\.from/);
  assert.match(content, /viewport/);
  assert.match(content, /approvalRequired/);
  assert.match(content, /document\.body\?\.innerText/);
  assert.match(content, /phantomSolana/);
  assert.match(pageActions, /phantomEthereum/);
  assert.match(pageActions, /phantomSolana/);
  assert.match(pageActions, /Wallet \/ DAO Audit/);
  assert.match(pageActions, /ResonantOS did not request wallet connection/);
  assert.doesNotMatch(pageActions, /\.connect\(/);
  assert.doesNotMatch(pageActions, /signMessage|signTransaction|signAndSendTransaction/);
  assert.match(pageActions, /chrome\.tabs\.sendMessage/);
  assert.match(pageActions, /phase/);
  assert.match(pageActions, /chrome\.scripting/);
  assert.match(pageActions, /executeScript/);
  assert.match(pageActions, /chrome\.webNavigation/);
  assert.match(pageActions, /mergeFrameSnapshots/);
  assert.doesNotMatch(content, /eval\(/);
  assert.doesNotMatch(panel, /eval\(/);
});

test("browser-first host is a runnable app path, not documentation-only scaffolding", async () => {
  const packageJson = await readJson(path.join(repoRoot, "package.json"));
  const launcher = await readText(path.join(browserFirstRoot, "host", "run-browser-first.mjs"));
  const bridgeServer = await readText(path.join(browserFirstRoot, "host", "bridge-server.mjs"));
  const installer = await readText(path.join(repoRoot, "scripts", "install-browser-first-app.mjs"));
  const nativeHost = await readText(
    path.join(repoRoot, "addons", "resonant-browser-native", "native_host", "src", "resonant_browser_native_host.cc"),
  );
  const nativeHostMac = await readText(
    path.join(repoRoot, "addons", "resonant-browser-native", "native_host", "src", "resonant_browser_native_host_mac.mm"),
  );
  const nativeHostInfoPlist = await readText(
    path.join(repoRoot, "addons", "resonant-browser-native", "native_host", "mac", "Info.plist.in"),
  );
  const nativeHelperInfoPlist = await readText(
    path.join(repoRoot, "addons", "resonant-browser-native", "native_host", "mac", "helper-Info.plist.in"),
  );

  assert.match(packageJson.scripts["browser-first:dev"], /run-browser-first\.mjs/);
  assert.match(packageJson.scripts["browser-first:install"], /install-browser-first-app\.mjs/);
  assert.match(installer, /ResonantOS Browser\.app/);
  assert.match(launcher, /--resonantos-browser-first/);
  assert.match(launcher, /resonantos-side-panel-extension/);
  assert.match(launcher, /bfnaelmomeimhlpmgjnjophhpkkoljpa/);
  assert.match(launcher, /pinned_extensions/);
  assert.match(launcher, /cdpdmmalhmokbfcfgogoepnjplaakgnl/);
  assert.match(launcher, /auto-open-side-panel/);
  assert.doesNotMatch(installer, /--auto-open-side-panel=true/);
  assert.match(launcher, /remote-debugging-port/);
  assert.match(launcher, /resonantos-remote-debugging-port/);
  assert.match(launcher, /createBridgeToken/);
  assert.match(launcher, /writeBridgeConfig/);
  assert.match(launcher, /startBridgeServer/);
  assert.match(bridgeServer, /bridge-config\.generated\.js/);
  assert.match(bridgeServer, /X-ResonantOS-Bridge-Token/);
  assert.match(bridgeServer, /X-ResonantOS-Bridge-Capability-Token/);
  assert.match(bridgeServer, /requiredCapability/);
  assert.match(bridgeServer, /Unauthorized browser-first bridge request/);
  assert.doesNotMatch(bridgeServer, /Access-Control-Allow-Origin": "\*"/);
  assert.match(launcher, /provider-secrets\.json/);
  assert.match(launcher, /providerRouteForWorkload/);
  assert.match(launcher, /workload \|\| "augmentor-chat"/);
  assert.match(launcher, /requiredCapability: "provider-credential-write"/);
  assert.match(launcher, /requiredCapability: "provider-routing-write"/);
  assert.match(launcher, /\/augmentor\/chat/);
  assert.match(launcher, /\/augmentor\/inline/);
  assert.match(launcher, /executeInlineAssistant/);
  assert.match(launcher, /customInstruction/);
  assert.match(launcher, /\/augmentor\/control-plan/);
  assert.match(launcher, /\/augmentor\/next-action/);
  assert.match(launcher, /executeNextAction/);
  assert.match(launcher, /sanitizeNextActionDecision/);
  assert.match(launcher, /switch_tab/);
  assert.match(launcher, /sanitizeControlStep/);
  assert.match(launcher, /sanitizeControlPlan/);
  assert.match(launcher, /executeControlPlan/);
  assert.match(launcher, /strict JSON only/);
  assert.match(launcher, /observed refs/);
  assert.match(launcher, /The web page remains in the main browser viewport/);
  assert.match(launcher, /host-mediated browser tools/);
  assert.match(launcher, /click visible page text/);
  assert.match(launcher, /\/memory\/status/);
  assert.match(launcher, /\/memory\/search/);
  assert.match(launcher, /\/archive\/intake/);
  assert.match(launcher, /\/addons\/delegate/);
  assert.match(launcher, /\/addons\/delegate\/list/);
  assert.match(launcher, /contextMarkdown/);
  assert.match(launcher, /sourceControlRunId/);
  assert.match(launcher, /Context Packet/);
  assert.match(launcher, /\/web\/news/);
  assert.match(launcher, /news\.google\.com\/rss/);
  assert.match(launcher, /keystroke \\"a\\" using \{option down, shift down\}/);
  assert.match(nativeHost, /resonantos-browser-first/);
  assert.match(nativeHost, /resonantos-remote-debugging-port/);
  assert.match(nativeHost, /CefKeyboardHandler/);
  assert.match(nativeHost, /EVENTFLAG_COMMAND_DOWN/);
  assert.match(nativeHost, /EVENTFLAG_CONTROL_DOWN/);
  assert.match(nativeHost, /IsPrimaryBrowserShortcut/);
  assert.match(nativeHost, /key_code == 'T'/);
  assert.match(nativeHost, /OpenNewBrowserSurface/);
  assert.match(nativeHost, /key_code == 'W'/);
  assert.match(nativeHost, /CloseBrowser\(false\)/);
  assert.match(nativeHost, /key_code == 'Q'/);
  assert.match(nativeHost, /CloseAllBrowserSurfaces/);
  assert.match(nativeHost, /kChromeNewTabFooterUrl/);
  assert.match(nativeHost, /chrome:\/\/newtab-footer/);
  assert.match(nativeHost, /Settings\/About/);
  assert.match(nativeHost, /browser\.first\.started/);
  assert.match(nativeHost, /resonantos-user-data-dir/);
  assert.match(nativeHost, /ExecuteNativeMenuCommand/);
  assert.match(nativeHost, /resonant_browser_native_execute_menu_command/);
  assert.match(nativeHost, /ExecuteChromeCommandByName/);
  assert.match(nativeHost, /cef_id_for_command_id_name/);
  assert.match(nativeHost, /CefContextMenuHandler/);
  assert.match(nativeHost, /GetContextMenuHandler/);
  assert.match(nativeHost, /OnBeforeContextMenu/);
  assert.match(nativeHost, /RunContextMenu/);
  assert.match(nativeHost, /OnContextMenuCommand/);
  assert.match(nativeHost, /OnContextMenuDismissed/);
  assert.match(nativeHost, /browser\.native\.context_menu\.before/);
  assert.match(nativeHost, /browser\.native\.context_menu\.run/);
  assert.match(nativeHost, /resonantos-context-menu-smoke/);
  assert.match(nativeHost, /IDC_NEW_TAB/);
  assert.match(nativeHost, /IDC_NEW_WINDOW/);
  assert.match(nativeHost, /IDC_CLOSE_TAB/);
  assert.match(nativeHost, /IDC_OPEN_FILE/);
  assert.match(nativeHost, /IDC_SAVE_PAGE/);
  assert.match(nativeHost, /IDC_FIND/);
  assert.match(nativeHost, /IDC_FIND_NEXT/);
  assert.match(nativeHost, /IDC_FIND_PREVIOUS/);
  assert.match(nativeHost, /IDC_VIEW_SOURCE/);
  assert.match(nativeHost, /IDC_DEV_TOOLS/);
  assert.match(nativeHost, /IDC_MANAGE_EXTENSIONS/);
  assert.match(nativeHost, /IDC_SHOW_HISTORY/);
  assert.match(nativeHost, /IDC_SHOW_DOWNLOADS/);
  assert.match(nativeHost, /IDC_CLEAR_BROWSING_DATA/);
  assert.match(nativeHost, /IDC_OPTIONS/);
  assert.match(nativeHost, /IDC_VIEW_PASSWORDS/);
  assert.match(nativeHost, /IDC_BOOKMARK_THIS_TAB/);
  assert.match(nativeHost, /IDC_SHOW_BOOKMARK_MANAGER/);
  assert.match(nativeHost, /IDC_MANAGE_CHROME_PROFILES/);
  assert.match(nativeHost, /IDC_SELECT_NEXT_TAB/);
  assert.match(nativeHost, /IDC_RESTORE_TAB/);
  assert.match(nativeHost, /GetZoomLevel/);
  assert.match(nativeHost, /SetZoomLevel/);
  assert.match(nativeHost, /SendEscapeKey/);
  assert.match(nativeHost, /CefDownloadHandler/);
  assert.match(nativeHost, /CefPermissionHandler/);
  assert.match(nativeHost, /GetDownloadHandler/);
  assert.match(nativeHost, /GetPermissionHandler/);
  assert.match(nativeHost, /CanDownload/);
  assert.match(nativeHost, /OnBeforeDownload/);
  assert.match(nativeHost, /OnDownloadUpdated/);
  assert.match(nativeHost, /OnRequestMediaAccessPermission/);
  assert.match(nativeHost, /OnShowPermissionPrompt/);
  assert.match(nativeHost, /browser\.native\.download_updated/);
  assert.match(nativeHost, /browser\.native\.permission\.prompt/);
  assert.match(nativeHost, /deny-by-default/);
  assert.match(nativeHost, /allow-resonant-mic/);
  assert.match(nativeHost, /allow-resonant-audio/);
  assert.match(nativeHost, /resonantos-download-smoke/);
  assert.match(nativeHost, /resonantos-permission-smoke/);
  assert.match(nativeHostMac, /ResonantInstallMainMenu/);
  assert.match(nativeHostMac, /setMainMenu/);
  assert.match(nativeHostMac, /resonant_browser_native_execute_menu_command/);
  assert.match(nativeHostMac, /ResonantOS Browser/);
  assert.match(nativeHostMac, /File/);
  assert.match(nativeHostMac, /Edit/);
  assert.match(nativeHostMac, /View/);
  assert.match(nativeHostMac, /Assistant/);
  assert.match(nativeHostMac, /History/);
  assert.match(nativeHostMac, /Bookmarks/);
  assert.match(nativeHostMac, /Profiles/);
  assert.match(nativeHostMac, /Tab/);
  assert.match(nativeHostMac, /Window/);
  assert.match(nativeHostMac, /Help/);
  assert.match(nativeHostMac, /copy:/);
  assert.match(nativeHostMac, /paste:/);
  assert.match(nativeHostMac, /selectAll:/);
  assert.match(nativeHostMac, /terminate:/);
  assert.match(nativeHostMac, /resonantNewTab:/);
  assert.match(nativeHostMac, /resonantOpenFile:/);
  assert.match(nativeHostMac, /resonantSavePage:/);
  assert.match(nativeHostMac, /resonantFind:/);
  assert.match(nativeHostMac, /resonantFindNext:/);
  assert.match(nativeHostMac, /resonantFindPrevious:/);
  assert.match(nativeHostMac, /resonantReloadPage:/);
  assert.match(nativeHostMac, /resonantViewSource:/);
  assert.match(nativeHostMac, /resonantDeveloperTools:/);
  assert.match(nativeHostMac, /resonantManageExtensions:/);
  assert.match(nativeHostMac, /resonantOpenAugmentor:/);
  assert.match(nativeHostMac, /resonantShowHistory:/);
  assert.match(nativeHostMac, /resonantShowDownloads:/);
  assert.match(nativeHostMac, /resonantClearBrowsingData:/);
  assert.match(nativeHostMac, /resonantBookmarkThisPage:/);
  assert.match(nativeHostMac, /resonantDefaultProfile:/);
  assert.match(nativeHostMac, /resonantManageProfiles:/);
  assert.match(nativeHostMac, /resonantPasswordManager:/);
  assert.match(nativeHostMac, /resonantSettings:/);
  assert.match(nativeHostMac, /resonantNextTab:/);
  assert.match(nativeHostMac, /resonantHelp:/);
  assert.match(nativeHostInfoPlist, /NSMicrophoneUsageDescription/);
  assert.match(nativeHelperInfoPlist, /NSMicrophoneUsageDescription/);
});

test("browser-first bridge rejects unauthenticated localhost requests", () => {
  const result = spawnSync(
    "node",
    [
      path.join(browserFirstRoot, "host", "run-browser-first.mjs"),
      "--bridge-auth-self-test=true",
      "--bridge-token=test-token",
      "--bridge-port=0",
    ],
    {
      cwd: repoRoot,
      encoding: "utf8",
      timeout: 10_000,
    },
  );

  assert.equal(result.status, 0, result.stderr || result.stdout);
  const payload = JSON.parse(result.stdout);
  assert.equal(payload.ok, true);
  assert.equal(payload.unauthorizedStatus, 401);
  assert.equal(payload.wrongTokenStatus, 401);
  assert.equal(payload.authorizedStatus, 200);
});
